privateApiKey: ${COMMON_PRIVATE_API_KEY}
trello:
    key: ${COMMON_TRELLO_KEY}
    token: ${COMMON_TRELLO_TOKEN}
trello2:
    key: ${COMMON_TRELLO_KEY2}
    token: ${COMMON_TRELLO_TOKEN2}
geekbot:
    key: ${COMMON_GEEKBOT_KEY}
slack:
    hookUrl: ${COMMON_SLACK_HOOK_URL}
    token: ${COMMON_SLACK_TOKEN}
guru:
    email: ${COMMON_GURU_EMAIL}
    token: ${COMMON_GURU_TOKEN}
secret: ${COMMON_SECRET}
wechat:
    tokenService: wechat-token-service.jiaoyin.cm
timezone: Asia/Shanghai

pigleaderboard:
    channel: '#general'
    boards: 'yOCWnVsn,PFvzorYj,ouTSW6bf,GAnfcNYs,4UkDF9pn,uEgAH6lk'
    standup: '5035'
    sentry:
        dsn: "http://18b52a1a1f0d4d3ea921fd5fbe8b0df2:bfe971b0d6ed4b87b958a7579e06341d@sentry.limijiaoyin.com/23"
    mongodb:
        host: 119.28.11.37
        port: 28193
        database: pigleaderboard

husky:
    trello:
        disabled: false
        leadBoard: 0FXlgVSI
    sentry:
        dsn: http://90abac4a55044c17907ee69bc6d8517f:6e39d3cac9134febb0299831bee14833@sentry.limijiaoyin.com/22
    mongodb:
        host: 119.28.11.37
        port: 21823
        database: husky
        
doberman:
    guruBoard: 1d25ed78-84a7-4ea9-941e-b5cd73979b31
    hostname: doberman-mobile.hk.jiaoyin.cm
    sentry:
        dsn: http://aaed2570008541ad9fcd09007285c192:0ddd8a87dcda452c983bd2606f1f1770@sentry.limijiaoyin.com/11
    trello:
        disabled: false
        freelancerBoard: JaUJzxLw
    auth:
        clientID: ${DOBERMAN_LIMIJIAOYIN_AUTH_CLIENT_ID}
        clientSecret: ${DOBERMAN_LIMIJIAOYIN_AUTH_CLIENT_SECRET}
    cache:
        host: 10.144.97.139
        port: 20197
    mongodb:
        host: 10.144.97.139
        port: 38819
        database: doberman
        username: ${DOBERMAN_DATABASE_USERNAME}
        password: ${DOBERMAN_DATABASE_PASSWORD}

dealer:
  slack:
    hook_url: https://hooks.slack.com/services/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
    channel: '#general'
  boards: yOCWnVsn,PFvzorYj,ouTSW6bf,GAnfcNYs,4UkDF9pn
