secret: foobar
mysql:
    host: localhost
    port: 3306
    username: root
    password: root
    database: words

consul:
    host: "192.168.1.10"
    port: 8500

api:
    host: "192.168.1.9"
    port: 7178

