privateApiKey: ${COMMON_PRIVATE_API_KEY}
trello:
    key: ${COMMON_TRELLO_KEY}
    token: ${COMMON_TRELLO_TOKEN}
geekbot:
    key: ${COMMON_GEEKBOT_KEY}
slack:
    hookUrl: ${COMMON_SLACK_HOOK_URL}
    token: ${COMMON_SLACK_TOKEN}
timezone: Asia/Shanghai
pigleaderboard:
    channel: '#general'
    boards: ''
    standup: ''
    sentry:
        dsn: ""
    mongodb:
        host: ""
husky:
    leadBoard: 0FXlgVSI
    trello:
        disabled: false
    sentry:
        dsn: http://90abac4a55044c17907ee69bc6d8517f:6e39d3cac9134febb0299831bee14833@sentry.limijiaoyin.com/22
    mongodb:
        host: ""  # 产品环境使用的 mongodb 配置，暂时无