privateApiKey: ${COMMON_PRIVATE_API_KEY}
qiniu:
    accessKey: 0V3pdbcLhNOuUTs71Q-ynVTx3CM8DJZ0Va5Y9BiF
    secretKey: RNB_fJHHlIEPT1W1gHarFf22VDBNj5qeo-34SS5N
    bucketName: statics
trello:
    key: ${COMMON_TRELLO_KEY}
    token: ${COMMON_TRELLO_TOKEN}
trello2:
    key: ${COMMON_TRELLO_KEY2}
    token: ${COMMON_TRELLO_TOKEN2}
geekbot:
    key: ${COMMON_GEEKBOT_KEY}
slack:
    hookUrl: ${COMMON_SLACK_HOOK_URL}
    token: ${COMMON_SLACK_TOKEN}
guru:
    email: ${COMMON_GURU_EMAIL}
    token: ${COMMON_GURU_TOKEN}
perdoo:
    username: ${COMMON_PERDOO_USERNAME}
    password: ${COMMON_PERDOO_PASSWORD}
xero:
    key: ${COMMON_XERO_KEY}
    secret: ${COMMON_XERO_SECRET}
secret: ${COMMON_SECRET}
wechat:
    tokenService: wechat-token-service.limijiaoyin.com
timezone: Asia/Shanghai

pigleaderboard:
    channel: '#general'
    boards: 'yOCWnVsn,PFvzorYj,ouTSW6bf,GAnfcNYs,98lO0FiB,Js4fIul5'
    standup: '5035'
    sentry:
        dsn: "http://18b52a1a1f0d4d3ea921fd5fbe8b0df2:bfe971b0d6ed4b87b958a7579e06341d@sentry.limijiaoyin.com/23"
    mongodb:
        host: 119.28.11.37
        port: 28193
        database: pigleaderboard

husky:
    trello:
        disabled: false
        leadBoard: 0FXlgVSI
        clientBoard: Gl8PvawP
        dealBoard: yGAGDF9P
        projectBoard: xYEmPkq3
        taskBoard: AIO64gwQ
        partnerBoard: UzU7fVMg
        channelBoard: SmghzuRK
    channel: '#marketing'
    sentry:
        dsn: http://90abac4a55044c17907ee69bc6d8517f:6e39d3cac9134febb0299831bee14833@sentry.limijiaoyin.com/22
    mongodb:
        host: 119.28.11.37
        port: 21823
        username: husky
        password: FAAC5CA6-75A8-4D56-B05F-F13EF39427B2
        database: husky
    google:
        dealFolderId: 0B63u_FwVZEHoOHdpY3dfNks0bVk
        contractFolderId: 0B63u_FwVZEHobmtFYm45dS04Q2s
    template:
        workload: 1TUxIrOdPQ3cFLnxNN53yLjmJKvrImDnlr9CJ-r9kN7w
        timesheet: 1a1xSB7ryPrqsq3-qaauyEddzqCLuHeFDeX0j95K1Fmc
    partners:
        guruBoard: 1d25ed78-84a7-4ea9-941e-b5cd73979b31
        auth:
            clientId: ${DOBERMAN_LIMIJIAOYIN_AUTH_CLIENT_ID}
            clientSecret: ${DOBERMAN_LIMIJIAOYIN_AUTH_CLIENT_SECRET}
        hostname: doberman-mobile.limijiaoyin.com

huskyData:
    mongodb: # 还没有上线第一版，配置先空着
        host: 119.28.11.37
        port: 21729
        username: ""
        password: ""
        database: huskyData


huskyMobile:
    auth:
        clientId: jcxSmXpY6kQLn89Sgfv79yRE4CYmuIuntEgz1lSK
        clientSecret: 9dFxRjc6Ophic86ijEaHZI5YFGH4lAtzocB6CE3iLsJoscBUiX6kBQr2fqVlCtFT6N20VvzknC2mRZPLc7ufiQ0BMzSwf4KVviVM4J4RMi6gqA5xAzY8tNTzEiDW8eyR
    hostname: husky-mobile.hk.jiaoyin.cm
    sentry:
        dsn: http://9de92f506b8d437584d1d5dfca5adaa2:9c6984ebf5d344cd809f7a8d5cb944da@sentry.limijiaoyin.com/26

samoyedNps:
    auth:
        clientId: z2etM6LZqCeqsZkd9gMqbs5J9IMqQce13Z7E2srN
        clientSecret: GSNyuiZ8foJiJ753AJVNz1m7xp9MtHHdcpoWo2CDVQPBkSr23XSQNcrNJs4HAchCMpyO7fBEV39PjGvPPi3B6Wjux7rnHm6r4ujuM46siHSLPnWsFm22c9Pn9n1knoaM
    hostname: samoyed-nps.hk.jiaoyin.cm
    sentry:
        dsn: http://3f37e915c6ee457da99061f8d04ac3bd:6effab1c3a5a4cffa22713e80752cc4c@sentry.limijiaoyin.com/27

doberman:
    sentry:
        dsn: http://aaed2570008541ad9fcd09007285c192:0ddd8a87dcda452c983bd2606f1f1770@sentry.limijiaoyin.com/11

dealer:
  slack:
    hook_url: https://hooks.slack.com/services/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
    channel: '#general'
  boards: yOCWnVsn,PFvzorYj,ouTSW6bf,GAnfcNYs,4UkDF9pn,Js4fIul5
  mongodb:
        host: 10.144.97.139
        port: 28037
        database: dealer

accounts:
    sentry:
        dsn: http://f92dc4410b6f4c9db827ced55c7c884c:b3316d016c054a78964499ea7251c45c@sentry.limijiaoyin.com/24
    mongodb:
        host: 10.144.97.139
        port: 28199
        username: accounts
        password: A41D3667-B377-40FE-B8CF-9D552E2BFD6C
        database: accounts

heartbeat:
    sentry:
        dsn: http://562f7f52c3e4498f8683ecc9206354b6:491849405bf14189bde40d9d834bde49@sentry.limijiaoyin.com/33

samoyed:
    trello:
        disabled: false
        reviewBoard: Wpf03xUX
    channel: '#service'
    sentry:
        dsn: http://3279a34655ba433f8a39ccb17dbe84c1:e5881328a455473c93dcfa97c3d65cb7@sentry.limijiaoyin.com/25
    mongodb:
        host: 119.28.11.37
        port: 28200
        username: samoyed
        password: C4F57CFD-A9D1-4F25-B66D-133E0B6CA3C2
        database: samoyed

resumeMotherFuckerWebService:
    mongodb:
        host: 10.144.97.139
        port: 41231
        database: rmf

files:
    sentry:
        dsn: http://f83272056f314b34abdd3420150b13b8:2fd36b80a8c14de2812673a8fe46231f@sentry.limijiaoyin.com/29

timesheetRecorder:
    mongodb:
        host: 10.144.97.139
        port: 62156
        database: timesheetRecorder

dealerboardBackend:
    hostname: dealer-board.limijiaoyin.com
    slack:
        clientId: '3025362346.124318311617'
        clientSecret: 0a26dfecc8358a09c7235e9a832d77e6
