redirectURI: https://dev.limibot.io/redirect
sentry:
  dsn: ""

slack:
  clientId: '3025362346.173210807556'
  clientSecret: cd51d296d6d92b48be64457f43670ea5

backend:
  host: up.dev.limibot.io
  webhooks:
    event-broker: https://event-broker.dev.limibot.io/api/v1/hook

event-broker:
  host: event-broker.dev.limibot.io

mongodb:
  host: 172.22.160.203
  port: 29341
  database: up
  username: ""
  passwrod: ""

redis:
  host: 172.22.160.203
  port: 47319
