huskyMobile:
    auth:
        clientId: arjdxKbaOe9Yhp6PuUh7nOCuWQx3cqgEGlUOD676
        clientSecret: 3O9YfOKRT7l489TqgmpSB9XhODCIpTJX0Tr0V7p1Xyicj6H6Gitm8f3ZbdIqZeb8F7Aju5WjfwvRtDrdJ4AYHtMmWmZbXs2nBSISLeuqFD64eaZNC3vJ4ov3uCptsTPg
    hostname: husky.io
