trello:
    key: e791ff75536084c7c796297f03f0da3e
    token: 6867f12e6a46957ac8f01a4166055d5a9cb841a3b5f5270f0fcab7553fa18ccb

husky:
    trello:
        disabled: false
        leadBoard: dlHZvMf5
        clientBoard: ""
        dealBoard: ""
        projectBoard: ""
        taskBoard: ""
        partnerBoard: ""
    mongodb:
        host: localhost
        port: 27017
        database: husky
        username: ""
        password: ""

