huskyMobile:
    auth:
        clientId: jcxSmXpY6kQLn89Sgfv79yRE4CYmuIuntEgz1lSK
        clientSecret: 9dFxRjc6Ophic86ijEaHZI5YFGH4lAtzocB6CE3iLsJoscBUiX6kBQr2fqVlCtFT6N20VvzknC2mRZPLc7ufiQ0BMzSwf4KVviVM4J4RMi6gqA5xAzY8tNTzEiDW8eyR
    hostname: husky.io
