husky:
    trello:
        disabled: true
    mongodb:
        host: localhost
        port: 27017
        database: husky
    partners:
        auth:
            clientId: zYgqDDBwfmJUamLUXKMcPJPzfS2Yv1ulQx5OM0bP
            clientSecret: RIGyRJMDVu4k7hGWG4egHLgdkgV8koumRUJfmUaKbsmpXakCUI1n9gahlodebwr2h9dkPXIkXQzUQGgzJm3mnMGEEDTxOrhWETiYGBC8uj4wHo3602ZQh9vSRsmDWNh1
        hostname: partners.io
    
