samoyedNps:
    auth:
        clientId: 7rIOC70NXxy5V01PwSWfGSeuMzLyPAvtYD2ffZMQ
        clientSecret: Ttu7IMevDsI6gJJDB7InJqt6V6Ob6UzzsVSVlJd2Jx0U1orqFURwYKgiT9Dpd78J2iZMwQ0Mo82m98xUNDffznktxtMpzxZzp3V8q8fi2fNb8HMphZ9VxrcmpdkRzWbX
    hostname: nps.io

