redirectURI: http://up.io/redirect
slack:
  clientId: '3025362346.173210807556'
  clientSecret: cd51d296d6d92b48be64457f43670ea5

backend:
  host: up.io
  webhooks:
    - http://event-broker.up.io/api/v1/hook

event-broker:
  host: event-broker.up.io

mongodb:
    host: 192.168.210.128
    port: 27017
    database: up
    username: ""
    passwrod: ""

