redirectURI: http://limibot.hk.limijiaoyin.io/redirect
sentry:
  dsn: ""

slack:
  clientId: '3025362346.210254285328'
  clientSecret: de9d99bcd4f9fd78aa46427a3c9de742

backend:
  host: up.io
  webhooks:
      event-broker: 'http://limibot-event-broker.hk.limijiaoyin.io/api/v1/hook'
  stripe:
    apiKey: sk_test_jD7uAOHePZpjKyVimquYz8tF

event-broker:
    host: 'http://limibot-event-broker.hk.limijiaoyin.io'

mongodb:
    host: 119.28.11.37
    port: 48171
    database: up
    username: ""
    passwrod: ""

redis:
  host: 119.28.11.37
  port: 12321

